name: mvp
type: laravel
docroot: public
php_version: "8.0"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.3"
provider: default
use_dns_when_possible: true
composer_version: "2"
webimage_extra_packages: [php8.1-imap]
web_environment: []
#hooks:
#  post-start:
#    - exec: "cat .env.example | sed  -E 's/DB_(HOST|DATABASE|USERNAME|PASSWORD)=(.*)/DB_\\1=db/g' > .env"
#    - exec: "php artisan key:generate"
#    - exec: "php artisan db:wipe"
#    - exec: "php artisan migrate"
#    - exec: "php artisan db:seed"
#    - exec: "npm i"
#    - exec: "npm run dev"
